columnSuffix: nrbhfvhw
contentColumnType: datetime
fieldGroup: 0634c691-f15a-4cdc-96ea-d3bacfad7546 # Global
handle: createdAtDateTime
instructions: null
name: created_at_date_time
searchable: false
settings:
  max: null
  min: null
  minuteIncrement: 5
  showDate: true
  showTime: true
  showTimeZone: false
translationKeyFormat: null
translationMethod: none
type: craft\fields\Date
