columnSuffix: ujgqhubw
contentColumnType: smallint(5)
fieldGroup: 0634c691-f15a-4cdc-96ea-d3bacfad7546 # Global
handle: price
instructions: 'Write a price for the product'
name: Price
searchable: false
settings:
  currency: EUR
  defaultValue: 0
  max: 10000
  min: 0
  showCurrency: false
  size: 4
translationKeyFormat: null
translationMethod: none
type: craft\fields\Money
