columnSuffix: utbhhtky
contentColumnType: text
fieldGroup: 0634c691-f15a-4cdc-96ea-d3bacfad7546 # Global
handle: summaryText
instructions: 'Write short one or two sentences'
name: 'Summary text'
searchable: false
settings:
  byteLimit: null
  charLimit: null
  code: false
  columnType: null
  initialRows: 4
  multiline: false
  placeholder: null
  uiMode: normal
translationKeyFormat: null
translationMethod: none
type: craft\fields\PlainText
